language: ruby
before_install: gem update --system
rvm:
  - 2.0.0
  - 2.1.0
notifications:
  slack: fastlane-tools:zSZhCfKthyIIZnSyODvyPBPQ
addons:
    code_climate:
        repo_token: 260bfcb1b7acf86c3a2424724879c02401d7fc9fc59ac7ca7dfa4b8c39bd1015